In [1]:
import numpy as np

### `np.meshgrid()`

#### `indexing="xy"`

In [2]:
a = np.array([0, 1, 2])
b = np.array([4, 5])

In [3]:
aa, bb = np.meshgrid(a, b, indexing="xy")  # same as np.meshgrid(a, b)
print("aa.shape: ", aa.shape)
print("bb.shape: ", bb.shape)

aa.shape:  (2, 3)
bb.shape:  (2, 3)


In [4]:
aa, bb

(array([[0, 1, 2],
        [0, 1, 2]]),
 array([[4, 4, 4],
        [5, 5, 5]]))

#### `indexing="ij"`

In [5]:
a = np.array([0, 1, 2])
b = np.array([4, 5])

In [6]:
aa, bb = np.meshgrid(a, b, indexing="ij")
print("aa.shape: ", aa.shape)
print("bb.shape: ", bb.shape)

aa.shape:  (3, 2)
bb.shape:  (3, 2)


In [7]:
aa, bb

(array([[0, 0],
        [1, 1],
        [2, 2]]),
 array([[4, 5],
        [4, 5],
        [4, 5]]))

#### `sparse=True`

In [8]:
a = np.array([0, 1, 2])
b = np.array([4, 5])

In [9]:
aa, bb = np.meshgrid(a, b, sparse=True)
print("aa.shape: ", aa.shape)
print("bb.shape: ", bb.shape)

aa.shape:  (1, 3)
bb.shape:  (2, 1)


In [10]:
aa, bb

(array([[0, 1, 2]]),
 array([[4],
        [5]]))